package me.truemb.tempfly.enums;

public enum CancelReason {
	
	SUCCESS, //EVERYTHING WORKED
	
	FLY_GAMEMODE, //USER IS IN SPECTATOR/CREATIVE
	FLY_IS_ALREAD_SET; //THE SET VALUE, IS ALREADY ON THE PLAYER

}
